# Generated by Django 5.0.7 on 2024-07-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CustomUser',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_details', models.TextField(max_length=100)),
                ('task_type', models.CharField(choices=[('Pending', 'pending'), ('Done', 'done')], max_length=100)),
                ('answer', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskapp.customuser')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
